services:
  - type: web
    name: virtual-try-on-studio
    env: node
    nodeVersion: 18.18.0
    buildCommand: |
      npm install -g pnpm@8.0.0
      pnpm install --no-frozen-lockfile
      pnpm build
    startCommand: pnpm preview --port $PORT
    envVars:
      - key: NODE_VERSION
        value: ">=18.0.0"
      - key: PNPM_VERSION
        value: ">=8.0.0"
      - key: NPM_FLAGS
        value: --legacy-peer-deps